// https://getintodevops.com/blog/building-your-first-docker-image-with-jenkins-2-guide-for-developers
properties([[$class: 'CopyArtifactPermissionProperty', projectNames: '*']])

def doBuild() {
    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */
        checkout scm
        sh "pwd"
    }
    stage("Copy artifacts") {
        dir ('qemu-cheri') {
            sh 'rm -rfv qemu-linux'
            copyArtifacts filter: 'qemu-linux/**', projectName: 'qemu/qemu-cheri'
            // Keep only the CHERI binaries
            sh 'cd qemu-linux/bin/ && rm -vf qemu-system-aarch64 qemu-system-riscv32 qemu-system-riscv64 qemu-system-mips64 qemu-system-x86_64'
            sh 'chmod -v +x qemu-linux/bin/* && ls -laR'
        }
    }
    dir ('qemu-cheri') {
        def app
        stage("Build image") {
            // sh "env | sort"
            sh "pwd && ls -la"
            app = docker.build("ctsrd/qemu-cheri", "--pull .")
            // Test that QEMU works:
            app.inside {
                sh "env | sort"
                sh '''
for i in cheri128 morello riscv64cheri;
do
    which qemu-system-$i
    qemu-system-$i --help > /dev/null
done
'''
            }
        }
        stage("Push image") {
            docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                app.push("${env.BUILD_NUMBER}")
                app.push("latest")
            }
        }
    }

    stage ("Cleaning up") {
        pwd
        sh "rm -rf qemu-cheri/qemu-linux"
        sh "ls -laR qemu-cheri"
    }
}

try {
    node("docker") {
        doBuild()
    }
} catch (e) {
    slackSend channel: '#jenkins', color: '#FF9FA1',
        message: "${env.JOB_NAME} ${env.BUILD_NUMBER} failed: ${e}! (<${env.BUILD_URL}|Open>)",
        tokenCredentialId: 'slack-token'
    currentBuild.result = 'FAILURE'
    throw e
}
